BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "EXPENSE" (
	"ID"	INTEGER NOT NULL,
	"MONTH"	TEXT NOT NULL,
	"DESCRIPTION"	TEXT NOT NULL,
	"VALUE"	INTEGER NOT NULL,
	"CREATED_AT"	DATETIME NOT NULL DEFAULT 0,
	"UPDATED_AT"	DATETIME NOT NULL DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ORDER" (
	"ID"	TEXT NOT NULL,
	"DATE"	DATE NOT NULL,
	"SUPPLIER"	TEXT NOT NULL,
	"SUPPLIER_NORMALIZED"	TEXT NOT NULL,
	"NFE_KEY"	TEXT,
	"FREIGHT"	INTEGER NOT NULL,
	"UNLOADING"	INTEGER NOT NULL,
	"CREATED_AT"	DATETIME NOT NULL DEFAULT 0,
	"UPDATED_AT"	DATETIME NOT NULL DEFAULT 0,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "PRODUCT" (
	"ID"	TEXT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"NAME_NORMALIZED"	TEXT NOT NULL,
	"QUANTITY"	INTEGER NOT NULL,
	"PRICE"	INTEGER NOT NULL,
	"PRICE_WITH_FREIGHT"	INTEGER NOT NULL,
	"TOTAL_PRICE"	INTEGER NOT NULL,
	"ORDER_ID"	TEXT NOT NULL,
	"ITEM_ORDINAL"	INTEGER,
	"CREATED_AT"	DATETIME NOT NULL DEFAULT 0,
	"UPDATED_AT"	DATETIME NOT NULL DEFAULT 0,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ORDER_ID") REFERENCES "ORDER"("ID")
);
COMMIT;
