from __future__ import annotations

from dataclasses import dataclass, field
from typing import Generic, TypeVar, List, Optional


T = TypeVar("T")


@dataclass
class OrderInput:
    """Data sent from the UI to save orders."""
    id: str
    date: str                      # YYYY-MM-DD
    supplier: str
    nfe_key: str = ""              # empty string -> NULL in DB
    freight: int = 0               # cents
    unloading: int = 0             # cents
    products: List[ProductInput] = field(default_factory=list)


@dataclass
class ProductInput:
    """Data sent from the UI for a single product line."""
    id: str
    name: str
    quantity: int
    price: int                     # unit price in cents
    total: int                     # total_price in cents
    order_id: str
    item_ordinal: Optional[int] = None


@dataclass
class ExpenseInput:
    """Data sent from the UI to save an expense."""
    description: str
    value: int                     # cents
    # ID is not sent from UI - auto-generated by DB


@dataclass
class PageResponse(Generic[T]):
    """Paginated response matching the Tauri PageResponse."""
    items: List[T]
    page: int
    page_count: int
    total: int                     # total number of matching rows
    page_size: int
