from __future__ import annotations

from datetime import datetime
from typing import List

from sqlalchemy import select, delete
from sqlalchemy.orm import Session, SessionTransaction

from backend.entities.orm import ExpenseEntity
from models.input import ExpenseInput


class ExpenseRepository:
    """Repository for the EXPENSE table using SQLAlchemy 2.0."""
    session: Session

    def __init__(self, db_session: Session | SessionTransaction) -> None:
        if isinstance(db_session, SessionTransaction):
            self.session = db_session.session
        elif isinstance(db_session, Session):
            self.session = db_session

    def fetch_expenses_for_month(self, month: str) -> List[ExpenseEntity]:
        """
        Fetch all expenses for a given YYYY-MM month.
        month format: "YYYY-MM" (e.g., "2024-07").
        """
        stmt = (
            select(ExpenseEntity)
            .where(ExpenseEntity.MONTH == month)
            .order_by(ExpenseEntity.ID.asc())
        )
        return list(self.session.execute(stmt).scalars().all())

    def delete_expenses_for_month(self, month: str) -> None:
        """Delete all expenses for a given month. Called inside a transaction."""
        stmt = delete(ExpenseEntity).where(ExpenseEntity.MONTH == month)
        self.session.execute(stmt)

    def insert_expense(self, expense: ExpenseInput, month: str) -> None:
        """Insert a single expense row. ID and timestamps are auto-generated by DB."""
        now = datetime.now()
        expense_entity = ExpenseEntity(
            MONTH=month,
            DESCRIPTION=expense.description,
            VALUE=expense.value,
            CREATED_AT=now,
            UPDATED_AT=now,
        )
        self.session.add(expense_entity)
