from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import List


@dataclass
class OrderInput:
    """Data sent from the UI to save orders."""
    id: str
    date: date  # YYYY-MM-DD
    supplier: str
    nfe_key: str = ""  # empty string -> NULL in DB
    freight: int = 0  # cents
    unloading: int = 0  # cents
    products: List[ProductInput] = field(default_factory=list)


@dataclass
class ProductInput:
    """Data sent from the UI for a single product line."""
    id: str
    name: str
    quantity: int
    price: int  # unit price in cents
    total: int  # total_price in cents
    order_id: str
    item_ordinal: int
    warnings: list[str] = field(default_factory=list)


@dataclass
class ExpenseInput:
    """Data sent from the UI to save an expense."""
    description: str
    value: int  # cents
    # ID is not sent from UI - auto-generated by DB
